[project]
name = "spotify_playlog"
version = "0.1.0"
description = "ETL Pipeline"
dependencies = []

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}